CREATE DATABASE bgi;
CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';
GRANT ALL ON bgi.* TO 'test'@'localhost';
FLUSH PRIVILEGES;
USE bgi;

CREATE TABLE users (
	id INT(16) UNSIGNED NOT NULL auto_increment PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	hash VARCHAR(256) NOT NULL,
	complexity INT(2) NOT NULL DEFAULT 10, 
	email VARCHAR(128),
	loginAttempts INT(2) NOT NULL DEFAULT 0
) ENGINE InnoDB;

CREATE TABLE lineitems (
	id INT(16) UNSIGNED NOT NULL auto_increment PRIMARY KEY,
	userId INT(16) UNSIGNED NOT NULL,
	name VARCHAR(256) NOT NULL,
	amountInCents INT(16) UNSIGNED NOT NULL DEFAULT 0,
	createdTime INT(16) UNSIGNED NOT NULL DEFAULT 1435445499, -- epoch time SELECT UNIX_TIMESTAMP(UTC_TIMESTAMP());
 	INDEX (`userId`),
	CONSTRAINT FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE InnoDB;