CREATE DATABASE bgi CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';
GRANT ALL ON bgi.* TO 'test'@'localhost';
FLUSH PRIVILEGES;
USE bgi;

CREATE TABLE users (
	id INT(16) UNSIGNED NOT NULL auto_increment PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	hash VARCHAR(256) NOT NULL,
	complexity INT(2) NOT NULL DEFAULT 10, 
	email VARCHAR(128),
	loginAttempts INT(2) NOT NULL DEFAULT 0
) ENGINE InnoDB COLLATE='utf8_unicode_ci';

CREATE TABLE lineitems (
	id INT(16) UNSIGNED NOT NULL auto_increment PRIMARY KEY,
	userId INT(16) UNSIGNED NOT NULL,
	name VARCHAR(256) NOT NULL,
	amountInCents INT(16) UNSIGNED NOT NULL DEFAULT 0,
	createdTime INT(16) UNSIGNED NOT NULL DEFAULT 1435445499, -- epoch time SELECT UNIX_TIMESTAMP(UTC_TIMESTAMP());
 	INDEX (`userId`),
	CONSTRAINT FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE InnoDB COLLATE='utf8_unicode_ci';

CREATE TABLE categories (
	id INT(16) UNSIGNED NOT NULL auto_increment PRIMARY KEY,
	userId INT(16) UNSIGNED NOT NULL,
	name VARCHAR(64) NOT NULL,
	balanceInCents INT(16) UNSIGNED NOT NULL DEFAULT 0,
	lastUpdated INT(16) UNSIGNED NOT NULL DEFAULT 1435445499,
	INDEX (`userId`),
	CONSTRAINT FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE InnoDB COLLATE='utf8_unicode_ci';

CREATE TABLE lineitem_categories (
	lineItemId INT(16) UNSIGNED NOT NULL,
	categoryId INT(16) UNSIGNED NOT NULL,
	CONSTRAINT FOREIGN KEY (`lineItemId`) REFERENCES `lineitems` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FOREIGN KEY (`categoryId`) REFERENCES `categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(lineItemId, categoryId)
) ENGINE InnoDB COLLATE='utf8_unicode_ci';